/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accesoabasededatos.view.ventanas;

/**
 *
 * @author franncode <github.com/franncode>
 */
public class AlumnosMenu extends javax.swing.JPanel {

    /**
     * Creates new form AlumnosMenu
     */
    public AlumnosMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreText = new javax.swing.JTextField();
        nombreLabel = new javax.swing.JLabel();
        nombreLabel1 = new javax.swing.JLabel();
        nombreText1 = new javax.swing.JTextField();
        buscarAlumnoButton = new keeptoo.KButton();
        miniWall = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreText.setBackground(new java.awt.Color(66, 18, 115));
        nombreText.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nombreText.setForeground(new java.awt.Color(255, 255, 255));
        nombreText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreText.setToolTipText("Nombre");
        nombreText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        nombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextActionPerformed(evt);
            }
        });
        add(nombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 310, 40));

        nombreLabel.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel.setText("Nombre");
        add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        nombreLabel1.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        nombreLabel1.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel1.setText("Apellido");
        add(nombreLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, -1, -1));

        nombreText1.setBackground(new java.awt.Color(66, 18, 115));
        nombreText1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nombreText1.setForeground(new java.awt.Color(255, 255, 255));
        nombreText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreText1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        nombreText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreText1ActionPerformed(evt);
            }
        });
        add(nombreText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 310, 40));

        buscarAlumnoButton.setText("Buscar alumno");
        buscarAlumnoButton.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        buscarAlumnoButton.setkBackGroundColor(new java.awt.Color(66, 18, 115));
        buscarAlumnoButton.setkEndColor(new java.awt.Color(66, 18, 115));
        buscarAlumnoButton.setkHoverEndColor(new java.awt.Color(66, 18, 115));
        buscarAlumnoButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        buscarAlumnoButton.setkHoverStartColor(new java.awt.Color(66, 18, 115));
        buscarAlumnoButton.setkSelectedColor(new java.awt.Color(51, 0, 51));
        buscarAlumnoButton.setkStartColor(new java.awt.Color(66, 18, 115));
        buscarAlumnoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAlumnoButtonActionPerformed(evt);
            }
        });
        add(buscarAlumnoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        miniWall.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        miniWall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accesoabasededatos/view/imgs/wall2.png"))); // NOI18N
        add(miniWall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void nombreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextActionPerformed

    private void nombreText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreText1ActionPerformed

    private void buscarAlumnoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAlumnoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarAlumnoButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton buscarAlumnoButton;
    private javax.swing.JLabel miniWall;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel nombreLabel1;
    private javax.swing.JTextField nombreText;
    private javax.swing.JTextField nombreText1;
    // End of variables declaration//GEN-END:variables
}
