/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package accesoabasededatos.view.ventanas;

/**
 *
 * @author franncode <github.com/franncode>
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        // Centra ventana en pantalla
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exitButton = new javax.swing.JLabel();
        nombreLabel = new javax.swing.JLabel();
        nombreText = new javax.swing.JTextField();
        buscarAlumnoButton = new keeptoo.KButton();
        Logo = new javax.swing.JLabel();
        materiasButton = new javax.swing.JLabel();
        homeButton = new javax.swing.JLabel();
        alumnosButton = new javax.swing.JLabel();
        nombreText1 = new javax.swing.JTextField();
        nombreLabel1 = new javax.swing.JLabel();
        wall = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accesoabasededatos/view/imgs/close.png"))); // NOI18N
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });
        getContentPane().add(exitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        nombreLabel.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        nombreLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel.setText("Nombre");
        getContentPane().add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        nombreText.setBackground(new java.awt.Color(66, 18, 115));
        nombreText.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nombreText.setForeground(new java.awt.Color(255, 255, 255));
        nombreText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreText.setToolTipText("Nombre");
        nombreText.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        nombreText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextActionPerformed(evt);
            }
        });
        getContentPane().add(nombreText, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 310, 40));

        buscarAlumnoButton.setText("Buscar alumno");
        buscarAlumnoButton.setFont(new java.awt.Font("Noto Serif", 0, 18)); // NOI18N
        buscarAlumnoButton.setkBackGroundColor(new java.awt.Color(66, 18, 115));
        buscarAlumnoButton.setkEndColor(new java.awt.Color(66, 18, 115));
        buscarAlumnoButton.setkHoverEndColor(new java.awt.Color(66, 18, 115));
        buscarAlumnoButton.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        buscarAlumnoButton.setkHoverStartColor(new java.awt.Color(66, 18, 115));
        buscarAlumnoButton.setkSelectedColor(new java.awt.Color(51, 0, 51));
        buscarAlumnoButton.setkStartColor(new java.awt.Color(66, 18, 115));
        buscarAlumnoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarAlumnoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(buscarAlumnoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, -1));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accesoabasededatos/view/imgs/logofinal.png"))); // NOI18N
        Logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 30, 200, -1));

        materiasButton.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        materiasButton.setForeground(new java.awt.Color(255, 255, 255));
        materiasButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        materiasButton.setText("Materias");
        getContentPane().add(materiasButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 200, 80));

        homeButton.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        homeButton.setForeground(new java.awt.Color(255, 255, 255));
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeButton.setText("Home");
        getContentPane().add(homeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 200, 80));

        alumnosButton.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        alumnosButton.setForeground(new java.awt.Color(255, 255, 255));
        alumnosButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        alumnosButton.setText("Alumnos");
        alumnosButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                alumnosButtonMouseClicked(evt);
            }
        });
        getContentPane().add(alumnosButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 200, 80));

        nombreText1.setBackground(new java.awt.Color(66, 18, 115));
        nombreText1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        nombreText1.setForeground(new java.awt.Color(255, 255, 255));
        nombreText1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nombreText1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        nombreText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreText1ActionPerformed(evt);
            }
        });
        getContentPane().add(nombreText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 310, 40));

        nombreLabel1.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        nombreLabel1.setForeground(new java.awt.Color(255, 255, 255));
        nombreLabel1.setText("Apellido");
        getContentPane().add(nombreLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 250, -1, -1));

        wall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/accesoabasededatos/view/imgs/ui1.png"))); // NOI18N
        getContentPane().add(wall, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarAlumnoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarAlumnoButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buscarAlumnoButtonActionPerformed

    private void nombreTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextActionPerformed

    private void nombreText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreText1ActionPerformed

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void alumnosButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_alumnosButtonMouseClicked

    }//GEN-LAST:event_alumnosButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel alumnosButton;
    private keeptoo.KButton buscarAlumnoButton;
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel homeButton;
    private javax.swing.JLabel materiasButton;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel nombreLabel1;
    private javax.swing.JTextField nombreText;
    private javax.swing.JTextField nombreText1;
    private javax.swing.JLabel wall;
    // End of variables declaration//GEN-END:variables
}
